name: DeathSwap
version: '${project.version}'
main: dev.derock.deathswap.DeathSwap
api-version: '1.20'
softdepend: ['Multiverse-Core']
commands:
  deathswap:
    description: DeathSwap command
    usage: /<command> [start|stop|reload]
    aliases: [ds]
    permission: deathswap.command
    permission-message: You don't have permission to use this command!