name: DeathSwap
version: '1.0-SNAPSHOT'
main: dev.derock.deathswap.DeathSwap
api-version: '1.20'
commands:
  deathswap:
    description: DeathSwap command
    usage: /<command> [start|stop|reload]
    aliases: [ds]
    permission: deathswap.command
    permission-message: You don't have permission to use this command!